Exercício 11
Algoritmo de Operaões Matématicas

inicio
inteiro n1, n2
real t_soma, t_sub, t_mult, t_div, t_rest

escreva("Escreva o 1º número")
leia(n1)

escreva("Escreva o 2º número")
leia(n2)


t_soma=n1+n1
t_sub=n1-n2
t_mult=n1*n2
t_div=n1/n2
t_rest=n1%n2

escreva("Resultado da soma" + t_soma)
escreva("Resultado da subtração" + t_sub)
escreva("Resultado da multiplicação" + t_mult)
escreva("Resultado da divisão " + t_div)
escreva("Resto" + t_rest) 

fim
