Exercício 2
Algoritmo Funcionario e Cargo ocupado


inicio

 literal funcionario,funcao
 inteiro dependentes

   escreva("Nome do funcionario ?")
     leia(funcionario)
   escreva("Número de dependentes ?")
     leia(dependentes)
   escreva("Cargo Ocupado ?")
     leia (funcao)

   escreva(funcionario + "possui" + dependentes + "dependente(s) e ocupado a função de" + funcao)

fim
