print("Digite o nome da primeira medicação:")
primeira_medicação=input()
print("Digite o valor da primeira medicação:")
int(valor_da_primeira_medicação=input())
print("Digite o nome da segunda medicação")
segunda_medicação=input()
print("Digite o valor da segunda medicação:")
int(valor_da_segunda_medicação=input()) 
print("Primeira medicação",primeira_medicação,"valor",valor_da_primeira_medicação)
print("Segunda medicação",segunda_medicação,"valor",valor_da_segunda_medicação)
print("Total"+int(valor_da_primeira_medicação) + int(valor_da_segunda_medicação))